### ISSUE TITLE
Error de arquitectura en paquetes de Graciela para Debian y Ubuntu i386 

### ISSUE THREAD

**Issue by jjca** [GracielaUSB/graciela-debian#1]
El archivo de control de los paquetes para Debian y Ubuntu i386 indican arquitectura amd64, impidiendo la instalación a menos se modifique manualmente y se reconstruyan los paquetes. (Cambié el formato a .txt para poder subir el archivo a GitHub)

[control_ubuntu_i386.txt](https://github.com/GracielaUSB/graciela-debian/files/870931/control_ubuntu_i386.txt)
[control_debian_i386.txt](https://github.com/GracielaUSB/graciela-debian/files/870932/control_debian_i386.txt)

**Comment by akrmn** [comment]
Closed by #2
